//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevToys.JsonPowerTool {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("DevToys.JsonPowerTool.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ShortDisplayTitle {
            get {
                return ResourceManager.GetString("ShortDisplayTitle", resourceCulture);
            }
        }
        
        internal static string LongDisplayTitle {
            get {
                return ResourceManager.GetString("LongDisplayTitle", resourceCulture);
            }
        }
        
        internal static string AccessibleName {
            get {
                return ResourceManager.GetString("AccessibleName", resourceCulture);
            }
        }
        
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        internal static string ModeBeautify {
            get {
                return ResourceManager.GetString("ModeBeautify", resourceCulture);
            }
        }
        
        internal static string ModeMinify {
            get {
                return ResourceManager.GetString("ModeMinify", resourceCulture);
            }
        }
        
        internal static string ModeTreeView {
            get {
                return ResourceManager.GetString("ModeTreeView", resourceCulture);
            }
        }
        
        internal static string ModeTableView {
            get {
                return ResourceManager.GetString("ModeTableView", resourceCulture);
            }
        }
        
        internal static string ModeQuery {
            get {
                return ResourceManager.GetString("ModeQuery", resourceCulture);
            }
        }
        
        internal static string ModeEntityConvert {
            get {
                return ResourceManager.GetString("ModeEntityConvert", resourceCulture);
            }
        }
        
        internal static string ModeSort {
            get {
                return ResourceManager.GetString("ModeSort", resourceCulture);
            }
        }
        
        internal static string SortAscendingButton {
            get {
                return ResourceManager.GetString("SortAscendingButton", resourceCulture);
            }
        }
        
        internal static string SortDescendingButton {
            get {
                return ResourceManager.GetString("SortDescendingButton", resourceCulture);
            }
        }
        
        internal static string InputTitle {
            get {
                return ResourceManager.GetString("InputTitle", resourceCulture);
            }
        }
        
        internal static string OutputTitle {
            get {
                return ResourceManager.GetString("OutputTitle", resourceCulture);
            }
        }
        
        internal static string QueryExpressionTitle {
            get {
                return ResourceManager.GetString("QueryExpressionTitle", resourceCulture);
            }
        }
        
        internal static string QueryLanguageJsonPath {
            get {
                return ResourceManager.GetString("QueryLanguageJsonPath", resourceCulture);
            }
        }
        
        internal static string QueryLanguageJMESPath {
            get {
                return ResourceManager.GetString("QueryLanguageJMESPath", resourceCulture);
            }
        }
        
        internal static string EntityLanguageLabel {
            get {
                return ResourceManager.GetString("EntityLanguageLabel", resourceCulture);
            }
        }
        
        internal static string SelectedNodePath {
            get {
                return ResourceManager.GetString("SelectedNodePath", resourceCulture);
            }
        }
        
        internal static string SelectedNodeValue {
            get {
                return ResourceManager.GetString("SelectedNodeValue", resourceCulture);
            }
        }
        
        internal static string TableViewNotApplicable {
            get {
                return ResourceManager.GetString("TableViewNotApplicable", resourceCulture);
            }
        }
        
        internal static string NoMatchesFound {
            get {
                return ResourceManager.GetString("NoMatchesFound", resourceCulture);
            }
        }
        
        internal static string JsonParseError {
            get {
                return ResourceManager.GetString("JsonParseError", resourceCulture);
            }
        }
        
        internal static string QueryResultTitle {
            get {
                return ResourceManager.GetString("QueryResultTitle", resourceCulture);
            }
        }
        
        internal static string GeneratedCodeTitle {
            get {
                return ResourceManager.GetString("GeneratedCodeTitle", resourceCulture);
            }
        }
        
        internal static string SortedJsonTitle {
            get {
                return ResourceManager.GetString("SortedJsonTitle", resourceCulture);
            }
        }
        
        internal static string QueryLanguageLabel {
            get {
                return ResourceManager.GetString("QueryLanguageLabel", resourceCulture);
            }
        }
        
        internal static string SortDirectionLabel {
            get {
                return ResourceManager.GetString("SortDirectionLabel", resourceCulture);
            }
        }
        
        internal static string SortDirectionAscending {
            get {
                return ResourceManager.GetString("SortDirectionAscending", resourceCulture);
            }
        }
        
        internal static string SortDirectionDescending {
            get {
                return ResourceManager.GetString("SortDirectionDescending", resourceCulture);
            }
        }
        
        internal static string LineLabel {
            get {
                return ResourceManager.GetString("LineLabel", resourceCulture);
            }
        }
        
        internal static string ColumnLabel {
            get {
                return ResourceManager.GetString("ColumnLabel", resourceCulture);
            }
        }
        
        internal static string InfoLabel {
            get {
                return ResourceManager.GetString("InfoLabel", resourceCulture);
            }
        }
    }
}
